import {
  BooksIcon,
  CakeIcon,
  CalendarHeartIcon,
  CheckCircleIcon,
  CoffeeIcon,
  CookingPotIcon,
  DropIcon,
  EnvelopeSimpleIcon,
  ExamIcon,
  FilmSlateIcon,
  FlowerTulipIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GiftIcon,
  HandHeartIcon,
  HeartIcon,
  IceCreamIcon,
  MoonIcon,
  MusicNotesIcon,
  NotebookIcon,
  PizzaIcon,
  RocketIcon,
  ShoppingBagIcon,
  SneakerIcon,
  SparkleIcon,
  StarIcon,
  TrophyIcon,
  type Icon,
} from "@phosphor-icons/react";

// Icons are stored by name in the database so they survive code changes.
export const ICONS: Record<string, Icon> = {
  heart: HeartIcon,
  gift: GiftIcon,
  flower: FlowerTulipIcon,
  "film-slate": FilmSlateIcon,
  coffee: CoffeeIcon,
  pizza: PizzaIcon,
  "envelope-simple": EnvelopeSimpleIcon,
  star: StarIcon,
  "fork-knife": ForkKnifeIcon,
  "calendar-heart": CalendarHeartIcon,
  "ice-cream": IceCreamIcon,
  "shopping-bag": ShoppingBagIcon,
  "music-notes": MusicNotesIcon,
  "game-controller": GameControllerIcon,
  cake: CakeIcon,
  sparkle: SparkleIcon,
  drop: DropIcon,
  sneaker: SneakerIcon,
  notebook: NotebookIcon,
  moon: MoonIcon,
  "hand-heart": HandHeartIcon,
  books: BooksIcon,
  "check-circle": CheckCircleIcon,
  "cooking-pot": CookingPotIcon,
  exam: ExamIcon,
  rocket: RocketIcon,
  trophy: TrophyIcon,
};

/** The 16 icons offered in the reward form. */
export const REWARD_ICONS = [
  "heart",
  "gift",
  "flower",
  "film-slate",
  "coffee",
  "pizza",
  "envelope-simple",
  "star",
  "fork-knife",
  "calendar-heart",
  "ice-cream",
  "shopping-bag",
  "music-notes",
  "game-controller",
  "cake",
  "sparkle",
] as const;

/** The icons offered in the activity form. */
export const ACTIVITY_ICONS = [
  "star",
  "drop",
  "sneaker",
  "notebook",
  "moon",
  "hand-heart",
  "books",
  "check-circle",
  "cooking-pot",
  "sparkle",
  "exam",
  "rocket",
  "trophy",
  "heart",
  "flower",
  "music-notes",
] as const;

export const ICON_LABELS: Record<string, string> = {
  heart: "Heart",
  gift: "Gift",
  flower: "Flower",
  "film-slate": "Film",
  coffee: "Coffee",
  pizza: "Pizza",
  "envelope-simple": "Letter",
  star: "Star",
  "fork-knife": "Dinner",
  "calendar-heart": "Date",
  "ice-cream": "Ice cream",
  "shopping-bag": "Shopping",
  "music-notes": "Music",
  "game-controller": "Games",
  cake: "Cake",
  sparkle: "Sparkle",
  drop: "Water",
  sneaker: "Walk",
  notebook: "Homework",
  moon: "Sleep",
  "hand-heart": "Kindness",
  books: "Study",
  "check-circle": "Done",
  "cooking-pot": "Cooking",
  exam: "Test",
  rocket: "Project",
  trophy: "Trophy",
};

export function NamedIcon({ name, size = 24, className }: { name: string; size?: number; className?: string }) {
  const Cmp = ICONS[name] ?? StarIcon;
  return <Cmp size={size} className={className} aria-hidden="true" />;
}
